apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rotiva-labs-ingress
  namespace: rotiva-labs-app
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: nginx.rotiva-labs.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rotiva-labs-svc
                port:
                  number: 80