apiVersion: v1
kind: Service
metadata:
  name: rotiva-labs-svc
  namespace: rotiva-labs-app
spec:
  selector:
    app: rotiva-labs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
